=== massfords/asl-path-validator/src/__tests__/json/example-schema.json
{
  "$id": "https://asl-path-validator.cloud/example.json#",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "Type": {
      "type": "string",
      "enum": ["Example"]
    },
    "OutputPath": {
      "type": "string",
      "format": "asl_path",
      "nullable": true
    },
    "InputPath": {
      "type": "string",
      "format": "asl_path",
      "nullable": true
    },
    "ResultPath": {
      "type": "string",
      "format": "asl_ref_path",
      "nullable": true
    },
    "TimeoutSecondsPath": {
      "type": "string",
      "format": "asl_ref_path",
      "nullable": true
    },
    "HeartbeatSecondsPath": {
      "type": "string",
      "format": "asl_ref_path",
      "nullable": true
    },
    "Parameters": {
      "$ref": "payload-template.json#"
    }
  },
  "required": ["Type"],
  "additionalProperties": false
}

=== massfords/asl-path-validator/src/__tests__/json/valid.json
{
  "Type": "Example",

  "OutputPath": "$.valid..path",

  "InputPath": "$.valid..path",

  "ResultPath": "$.valid.ref.path",

  "TimeoutSecondsPath": "$.valid.ref.path",

  "Parameters": {
    "static$": {
      "dynamic.path1.$": "$.valid..path",
      "dynamic.path2.$": "States.StringToJson($.someString)",
      "dynamic.path3.$": "$.fooList[1:]"
    }
  }
}
